
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD AP DIV FP MUL NUMBER SUBop : expressop : op ADD calcop : op SUB calccalc : NUMBERcalc : calc MUL NUMBER calc : calc DIV NUMBER express : NUMBERexpress : AP op FP'
    
_lr_action_items = {'NUMBER':([0,4,5,6,12,13,],[3,3,9,9,14,15,]),'AP':([0,4,],[4,4,]),'$end':([1,2,3,8,9,10,11,14,15,],[0,-1,-7,-2,-4,-3,-8,-5,-6,]),'ADD':([1,2,3,7,8,9,10,11,14,15,],[5,-1,-7,5,-2,-4,-3,-8,-5,-6,]),'SUB':([1,2,3,7,8,9,10,11,14,15,],[6,-1,-7,6,-2,-4,-3,-8,-5,-6,]),'FP':([2,3,7,8,9,10,11,14,15,],[-1,-7,11,-2,-4,-3,-8,-5,-6,]),'MUL':([8,9,10,14,15,],[12,-4,12,-5,-6,]),'DIV':([8,9,10,14,15,],[13,-4,13,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'op':([0,4,],[1,7,]),'express':([0,4,],[2,2,]),'calc':([5,6,],[8,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> op","S'",1,None,None,None),
  ('op -> express','op',1,'p_op_1','anasin.py',5),
  ('op -> op ADD calc','op',3,'p_op_2','anasin.py',9),
  ('op -> op SUB calc','op',3,'p_op_3','anasin.py',13),
  ('calc -> NUMBER','calc',1,'p_cacl_1','anasin.py',17),
  ('calc -> calc MUL NUMBER','calc',3,'p_calc_2','anasin.py',21),
  ('calc -> calc DIV NUMBER','calc',3,'p_calc_3','anasin.py',25),
  ('express -> NUMBER','express',1,'p_express_1','anasin.py',29),
  ('express -> AP op FP','express',3,'p_express_2','anasin.py',33),
]
